### ISSUE TITLE
droxi with on deman access to multiple accounts

### ISSUE THREAD

**Issue by severach** [jangler/droxi#11]
Currently there's only one account per user. I'd like a command line option or a keyword that lets me specify which account I want to connect to.

dropbox-uploader uses the -f option for this.

**Comment by jangler** [comment]
This is a good idea. I'll have to think about how to implement this in a backward-compatible way.

**Comment by severach** [comment]
Some will want this implemented like gpg key chains or ssh keys where a single file has all the info. Add, list store, and remove would be managed by droxi. This could lead into some nifty features like automatically picking the store based on the source files.

I would prefer each account to be a separate file the way dropbox-uploader does. I can add or remove accounts just by adding or removing files, or just specifying any file.

**Comment by jangler** [comment]
Implemented and included in v0.4.0. The `-f` option was the natural way to go, dropbox-uploader style. If you specify a file that doesn't exist, droxi will create it after you authorize a new account.

For reference, the default config file is at `~/.config/droxi/droxirc`.
