### ISSUE TITLE
!cd command does not work

### ISSUE THREAD

**Issue by severach** [jangler/droxi#12]
This is probably because cd is a builtin and droxi only looks for executables

For more entertainment try !mc, !vi, or !vim

**Comment by jangler** [comment]
Yes, `!cd` doesn't work because cd is a shell builtin. Use `lcd` instead. Usage of curses-type applications could possibly be solved by using `exec`. I'll look into this.

**Comment by jangler** [comment]
Implemented and included in v0.4.0. It should be "safe" to exec whatever you want now.
