### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by beelze** [jangler/droxi#16]
I'm making an ebuild for droxi and I need an exact dependencies. As I see, it is a dropbox-sdk-*.gem at least? What ruby versions?

**Comment by jangler** [comment]
According to the gemspec:

>  s.add_runtime_dependency 'dropbox-sdk', '~> 1.6', '>= 1.6.4'
 > s.required_ruby_version = '>= 2.0.0'

**Comment by beelze** [comment]
Thanks, got it.
