### ISSUE TITLE
Exit codes always 0?

### ISSUE THREAD

**Issue by beelze** [jangler/droxi#17]
I've tested some commands and never saw exitcode !=0 even when failed:
```
% droxi share blahblah
share: blahblah: no such file or directory (exitcode is 0)
```
Is it intended behaviour? Maybe we can use non-zero exitcode at least sometimes?

**Comment by jangler** [comment]
If I remember correctly, I would have liked this but didn't implement it due to some sort of awkwardness owing to the non-interactive usage being sort of second-class. Definitely worth another look…

**Comment by beelze** [comment]
Good… it's so ugly to parse output to get success/failure status
