### ISSUE TITLE
Silent quit or error when --help or --version

### ISSUE THREAD

**Issue by roomcays** [jangler/droxi#18]
With version v0.5.0 running just `droxi` does not start interactive mode anymore. CLI commands also stopped working.

However, when invoking `droxi` with `--help` or `--version` argument, following error occurs:

```
$ droxi --version
droxi v0.5.0
/home/user/.gem/ruby/2.4.0/gems/droxi-0.5.0/lib/droxi.rb:54:in `ensure in run': undefined method `exit_status' for nil:NilClass (NoMethodError)
	from /home/user/.gem/ruby/2.4.0/gems/droxi-0.5.0/lib/droxi.rb:54:in `run'
	from /home/user/.gem/ruby/2.4.0/gems/droxi-0.5.0/bin/droxi:3:in `<top (required)>'
	from /home/user/.gem/ruby/2.4.0/bin/droxi:23:in `load'
	from /home/user/.gem/ruby/2.4.0/bin/droxi:23:in `<main>'
```

I love the idea of using CLI and API to selectively sync files with FTP-alike commands, so I'd love to help to fix the issue. However I'm not a Ruby programmer at all (but I still may try to do something when guided!).

**Comment by jangler** [comment]
See #15. Working on it.
