### ISSUE TITLE
Add git remotehelper

### ISSUE THREAD

**Issue by anatol** [jangler/droxi#6]
Thanks for this useful tool that allows to use Dropbox without copying whole folder.

One of very useful applications for it could be using Dropbox as git repository storage. git allows to use pluggable remote helpers. It would be great to have "droxi::" protocol support that allows git to use droxi transparently with minimum efforts.

See `man gitremote-helpers` that describes list of commands that remotehelper should support.

**Comment by jangler** [comment]
That's an interesting idea, but it's beyond the scope of what I'm willing to do with droxi at the moment. If at some point other users weigh in and communicate a desire for this feature, I will consider implementing it.

**Comment by anatol** [comment]
Thanks for your reply.

Yeah, it is probably better to have such script as a separate project based on Dropbox API.
