### ISSUE TITLE
Feature Request: Put with move option

### ISSUE THREAD

**Issue by severach** [jangler/droxi#9]
Please add a move with delete option to put. The move must behave atomically. The file must be deleted if the upload was successful. The file must not be deleted if the upload was not successful or was partial.

**Comment by jangler** [comment]
Can you clarify what you mean by "move"? What is being moved where, and under what conditions, during a put operation when this option is used?

**Comment by severach** [comment]
See lftp option "put -E" and "mput -E"

-E           delete source files after successful transfer (dangerous)

See winscp -delete

http://winscp.net/eng/docs/faq_delete_synchronized_files

It's only dangerous with hand typed commands. When lftp or droxi is used in scripts, the script always ensures that the file to be sent is a copy that must be deleted on successful send. My script copies the files to be sent into a queue folder. The send tool (lftp or droxi) deletes the files to show they have been sent. Files that are still in the queue are presumed there because of a transfer error and a list gets emailed to an operator. Occasional errors are to be expected but repeated failures must be checked out.

Note that as part of the atomic operation each file must be deleted right after transfer. You can't transfer a bunch of files then delete them. If droxi crashes or the Internet goes down in the middle the right files must be deleted.

I only need it on the put command so that the local file is deleted when transferred into dropbox. I'm sure others will need a move/delete option on the get command to delete the file on dropbox when the file has been transferred locally.

See lftp "mget -E" and "get -E"

**Comment by jangler** [comment]
Thanks, that makes sense to me. I will implement this for 'put' and 'get' in the next minor version.

**Comment by jangler** [comment]
Implemented per your spec for both 'put' and 'get' in b80f780. This change is included in the current version, 0.3.1.
